### PR TITLE
Get QuIRC ready

### PR DESCRIPTION
**Pull request by RhinosF1**
Per [T4436](https://phabricator.miraheze.org/T4436)

### CODE REVIEW

**Comment by RhinosF1** [comment]
I need to set up a LIST of proded articles but I'll wait until the templates are ready and make instructions even more PROD-like.


See the phab task for what to remove.

Thanks,
RhinosF1

PS: Anyone capable can help with this

**Comment by LakesideMiners** [comment]
Merging, I will get a list of the templates that need to be imported. the {{QuickDel|1=Reason (include criteria code below)}}  thing won't work because TW adds templates, from pages, I can make the needed templates when I get the time as we can't seem to get the ones imported from enwiki to look right.

**Comment by LakesideMiners** [comment]
Merged, tagging with "Done Successfully"

**Comment by RhinosF1** [comment]
You can scrap QuickDel template.

Just let me know via the Phab task and I'll process when everything is set up.

Have you checked the enwp templates?

What's the error?

**Pull request merged**
